### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [fewbytes-cookbooks/artifactory#5]
This is what I'm getting when trying to use the package:

```
NoMethodError
-------------
undefined method `[]' for nil:NilClass


Cookbook Trace:
---------------
  /vagrant/cookbooks/build-essential/recipes/rhel.rb:39:in `block (2 levels) in from_file'
  /vagrant/cookbooks/build-essential/recipes/rhel.rb:38:in `block in from_file'
  /vagrant/cookbooks/build-essential/recipes/rhel.rb:36:in `each'
  /vagrant/cookbooks/build-essential/recipes/rhel.rb:36:in `from_file'
  /vagrant/cookbooks/build-essential/recipes/default.rb:21:in `from_file'
  /vagrant/cookbooks/runit/recipes/default.rb:42:in `from_file'
  /vagrant/cookbooks/artifactory/recipes/default.rb:12:in `from_file'
  /vagrant/cookbooks/foo/recipes/default.rb:9:in `from_file'


Relevant File Content:
----------------------
/vagrant/cookbooks/build-essential/recipes/rhel.rb:

 32:  if node['platform_version'].to_i < 6
 33:    pkgs.unshift %w{ gcc44 gcc44-c++ }
 34:  end
 35:  
 36:  pkgs.flatten.each do |pkg|
 37:  
 38:    r = package pkg do
 39>>     action( node['build_essential']['compiletime'] ? :nothing : :install )
 40:    end
 41:    r.run_action(:install) if node['build_essential']['compiletime']
 42:  
 43:  end
 44:  
```

Any ideas?

**Comment by nukemberg** [comment]
this looks like a bug in the build-essential cookbook.
